### ISSUE TITLE
install Rich Python package

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#125]
Having [Rich](https://pypi.org/project/rich) installed lets EasyBuild show progress bars while it is installing software, see https://docs.easybuild.io/en/latest/Progress_bars.html

See [`dev-python/rich`](https://packages.gentoo.org/packages/dev-python/rich), looks like it's not being packaged yet for `aarch64` and `ppc64le`?

It's not a blocker if it's difficult to install everywhere, just nice to have, it doesn't affect the actual software installations themselves, just the terminal output produced by EasyBuild during the installation.

**Comment by amadio** [comment]
You can try to use `package.accept_keywords` to install `dev-python/rich` for other arches... It's probably just not keyworded yet. If it works, just file a bug so the maintainer adds the keywords for aarch64 and ppc64 in gentoo.

**Comment by bedroge** [comment]
This is now part of our set files for 2021.12. I'll leave the issue open so that we can verify if it works on `aarch64` and `ppc64le`, and file a bug if it does.

**Comment by boegel** [comment]
fixed by including `dev-python/rich` in 2021.12 set, see https://github.com/EESSI/gentoo-overlay/pull/56, so closing...
