### ISSUE TITLE
problems with glibc 2.34 in compat layer

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#137]
* bootstrapping Prefix with glibc 2.34 is broken, see https://bugs.gentoo.org/824482
* known incompatibility with GCC 11 + CUDA, see also https://forums.developer.nvidia.com/t/cuda-11-5-samples-throw-multiple-error-attribute-malloc-does-not-take-arguments/192750 (hat tip @amadio)

**Comment by bedroge** [comment]
We masked this version for `2021.12`, see: https://github.com/EESSI/compatibility-layer/pull/126/commits/2cbd6154e235f332bfbcb70dee25acfde8d217c0 and https://github.com/EESSI/compatibility-layer/pull/126/commits/20206a53999737241cac6821afb10ad49a60b3f5

**Comment by boegel** [comment]
We worked around this for EESSI pilot 2021.12 by masking glibc >= 2.34, and CUDA 11.x is now compatible according to https://forums.developer.nvidia.com/t/cuda-11-5-samples-throw-multiple-error-attribute-malloc-does-not-take-arguments/192750, so closing this...
