### ISSUE TITLE
add symlink for var/log/wtmp

### ISSUE THREAD

**Issue by trz42** [EESSI/compatibility-layer#149]
last accesses the file `var/log/wtmp` in a compatibility layer, for example, `/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/var/log/wtmp`.

That file however doesn't exist. It should be a symlink to the host's wtmp file, most likely, `/var/log/wtmp`.

One might also consider to symlink to `/var/log`, then however, existing content in `/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/var/log` requires a new location.

A temporary workaround for getting last to work would be to run
```
last -f /var/log/wtmp
```

**Comment by amadio** [comment]
According to the man page, you may want to also link `/var/log/btmp`.

**Comment by bedroge** [comment]
Should be fixed by #199.
