### ISSUE TITLE
pip check fails in 2021.12

### ISSUE THREAD

**Issue by trz42** [EESSI/compatibility-layer#152]
Some package in the compatibility layer of 2021.12 is missing as reported by pip check. Reproduce as follows

$ source /cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/bash
...
$ pip check
gitpython 3.1.24 requires typing-extensions, which is not installed.

The problem has actually been reported to gentoo, see https://bugs.gentoo.org/827882
The fix, however, was not used to bootstrap the prefix. It seems the specific commit being used (https://github.com/gentoo/gentoo/commit/7eaa2512d1e6ddb44e3b41bbddf6c74723f234ce) is two days too old.

It might be possible to fix this with an in-place update of the package.

**Comment by boegel** [comment]
We should probably add `pip check` to the tests that are run for the compat layer, because EasyBuild relies on `pip check` during the sanity check of Python packages...
