### ISSUE TITLE
Failing tests with newer Lmod versions

### ISSUE THREAD

**Issue by bedroge** [EESSI/compatibility-layer#153]
@ocaisa requested a newer version of Lmod. I gave it a quick try, but a lot of tests are failing for the latest version. Also tried some slightly older versions, and it looks like the issues start around version 8.5.2x. Haven't had time yet to inspect all the logs and figure out what's wrong...

**Comment by boegel** [comment]
Does @amadio's issue at https://github.com/TACC/Lmod/issues/543 help at all?

**Comment by amadio** [comment]
I've just bumped Hermes and Lmod, should solve the test failures. Let me know if you still have problems with Lmod 8.6.14.

**Comment by bedroge** [comment]
Seems to work fine for the latest version in the gentoo repo, so closing this issue.
