### ISSUE TITLE
Lmod ebuild in gentoo-overlay is missing dep on luaposix

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#17]
`emerge Lmod` fails with:

```
Error: The follow lua module(s) are missing:  posix

You can not run Lmod without:  posix
```

fixed after `emerge dev-lua/luaposix`

**Comment by boegel** [comment]
Strange though, since `dev-lua/luaposix` is listed as a dep at https://github.com/EESSI/gentoo-overlay/blob/6abe27db39f78c6d4ed53b3552358efa04d77f59/app-admin/Lmod/Lmod-8.3.17.ebuild#L15-L16...

**Comment by bedroge** [comment]
Hmm, weird, don't think I had that issue with my playbook (see #12)...

**Comment by boegel** [comment]
@bedroge In hindsight, this was probably self-inflicted...

I had installed `dev-lua/luaposix` manually with `emerge dev-lua/luaposix` before adding the overlay, which was for a different version of Lua than the one Lmod is being installed with through `gentoo-overlay` (Lua 5.1 with standard Gentoo Prefix, Lua 5.3 with `gentoo-overlay`).

So, closing...
