### ISSUE TITLE
add profile for `arm64` to gentoo

### ISSUE THREAD

**Issue by trz42** [EESSI/compatibility-layer#171]
It seems building the compatibility layer for `aarch64` is currently broken because a profile for `arm64` is missing. See https://bugs.gentoo.org/892876

Ideally this would be fixed by making a PR to gentoo.

In the meantime we can try to use the workaround described in https://bugs.gentoo.org/892876

**Comment by trz42** [comment]
#176 includes the workaround described in https://bugs.gentoo.org/892876

**Comment by bedroge** [comment]
Fixed in https://github.com/gentoo/gentoo/pull/30568.
