### ISSUE TITLE
Gentoo Prefix bootstrap script fails due to missing configure for bzip2

### ISSUE THREAD

**Issue by bedroge** [EESSI/compatibility-layer#2]
See https://bugs.gentoo.org/728682

For now we can use an older version of the script, e.g. this one:
https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh?id=ad5ab57d7ce52784d597298c13265c617dbf507c

**Comment by boegel** [comment]
@bedroge Should we copy that script in our repo?

We may have to customize is like ComputeCanada did?

**Comment by bedroge** [comment]
Yes, we probably should copy it at some point (but when / which version?) and make the required (not sure how many yet) modifications.

**Comment by boegel** [comment]
Let's use a version that works. :P

And try to keep an eye on upstream changes. I'm a bit worried that it's hard broken without them noticing though...
Maybe we should run it in CI ourselves? Not sure if that's feasible if it takes hours.

**Comment by bedroge** [comment]
Yes, it does take a very long time to complete. From what I found in the docs, Github Actions have a maximum execution time of 6 hours. Don't know if that's enough... But it would be useful to run this script every once in a while.

**Comment by boegel** [comment]
We could consider a self-hosted runner in a VM for it?

https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by bedroge** [comment]
The bug has been fixed. Let's continue the discussion on the installation method in #3 .
