### ISSUE TITLE
Location to store a copy of gentoo snapshot for bootstrapping the prefix

### ISSUE THREAD

**Issue by peterstol** [EESSI/compatibility-layer#26]
The prefix installation script uses by default the latest portage and gentoo snapshots from http://distfiles.gentoo.org/snapshots/. 

We would like to use a specific snapshot to install the prefix for reproducibility. As the snapshots are only kept for a limited timeframe on gentoo.org an alternative location is required. Due to space concerns, our github repo is not considered suitable. The location will be referenced by setting SNAPSHOT_URL in the prefix bootstrap script.

**Comment by bedroge** [comment]
Some options that have been mentioned:

- On our website; does it have enough space + bandwidth?
- In a separate git repo
- On CVMFS -> would that work?

**Comment by bedroge** [comment]
Since the Stratum 0 is just a web server anyway, I think we could also store them on that machine.

**Comment by bedroge** [comment]
I put them on the stratum 0 (http://cvmfs-s0.eessi-hpc.org/snapshots/) and tested this with a small change in the bootstrap script, and that worked. I'll make a PR for this.

**Comment by bedroge** [comment]
See #31.
