### ISSUE TITLE
Unmasking packages for aarch64 support.

### ISSUE THREAD

**Issue by terjekv** [EESSI/compatibility-layer#35]
Lmod and archspec are not supported on aarch64 by default.

```
emerge --ask --autounmask=y --autounmask-write =app-admin/Lmod-8.3.17
emerge --ask --autounmask=y --autounmask-write =sys-apps/archspec-0.1.1
dispatch-conf
```

**Comment by terjekv** [comment]
Also, `dev-lua/luaposix-35.0` installs into `/lib` and not `lib64`. Works after `cd $EPREFIX; cp -uav usr/lib/lua/5.1/* usr/lib64/lua/5.1/`

**Comment by bedroge** [comment]
I think the archspec issue (assuming you had the same issue as I had, about Python 2.7) should be solved by:
https://github.com/EESSI/gentoo-overlay/pull/16

**Comment by bedroge** [comment]
https://github.com/EESSI/gentoo-overlay/pull/18
This PR might partially solve the Lmod issue. Still need to look at the Lua issues, but unfortunately I don't have an Arm machine ;-)

**Comment by bedroge** [comment]
I hope/expect all these issues should be solved by PR https://github.com/EESSI/gentoo-overlay/pull/18.

**Comment by terjekv** [comment]
https://github.com/EESSI/gentoo-overlay/pull/20 takes care of the rest of the issues.

**Comment by boegel** [comment]
All merged, so I'm assuming we can close this...

**Comment by terjekv** [comment]
Yep!
