### ISSUE TITLE
Duplicate repository name entries.

### ISSUE THREAD

**Issue by terjekv** [EESSI/compatibility-layer#43]
Very low priority, but worth noting anyway:

```
WARNING: One or more repositories have been ignored due to duplicate
  profiles/repo_name entries:

  /cvmfs/pilot.eessi-hpc.org/2020.09/compat/aarch64/, gentoo, /cvmfs/pilot.eessi-hpc.org/2020.09/compat/aarch64/var/db/repos/gentoo overrides
    /cvmfs/pilot.eessi-hpc.org/2020.09/compat/aarch64/tmp/var/db/repos/gentoo

  All profiles/repo_name entries must be unique in order to avoid having
  duplicates ignored. Set PORTAGE_REPO_DUPLICATE_WARN="0" in
  /etc/portage/make.conf if you would like to disable this warning.

```

**Comment by bedroge** [comment]
Do you still remember how you triggered this warning? Sounds like maybe `eselect repository add` was run multiple times with duplicate names. If you still have this installation, could you post the contents of `$EPREFIX/etc/portage/repos.conf/eselect-repo.conf`?

**Comment by terjekv** [comment]
The machine that had this data is still offline, but I think you're right in that `select repository add` was run multiple times. I'm not sure why it happened, and I haven't seen it since. :-(

**Comment by peterstol** [comment]
We can reopen if it is seen again ;-)
