### ISSUE TITLE
Add architecture tag to all prefix docker containers.

### ISSUE THREAD

**Issue by terjekv** [EESSI/compatibility-layer#52]
Right now https://hub.docker.com/r/eessi/client-pilot/tags has a bit of a hodgepodge usage of tags. We should standardise on both the format and have architecture tags for all archs, not just "non-x86_64".

**Comment by boegel** [comment]
New images with `x86_64` and `aarch64` in the tag are now available at https://hub.docker.com/r/eessi/bootstrap-prefix/tags, so you can use `docker://eessi/bootstrap-prefix:centos8-$(uname -m)`.

These images were built and pushed using the script included in #50
