### ISSUE TITLE
lib vs lib64 in Prefix installation differs between architectures

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#63]
The `/lib` and `/lib64` directories in the compat layer are handled differently on `x86_64` vs `aarch64`:

```
$ ls -ld /cvmfs/pilot.eessi-hpc.org/2020.10/compat/{aarch64,x86_64}/{lib,lib64}                                 
drwxr-xr-x 2 ec2-user ec2-user 4096 Nov  3 20:35 /cvmfs/pilot.eessi-hpc.org/2020.10/compat/aarch64/lib
drwxr-xr-x 2 ec2-user ec2-user 4096 Nov  3 20:39 /cvmfs/pilot.eessi-hpc.org/2020.10/compat/aarch64/lib64
lrwxrwxrwx 1 ec2-user ec2-user    5 Oct 30 00:32 /cvmfs/pilot.eessi-hpc.org/2020.10/compat/x86_64/lib -> lib64
drwxr-xr-x 2 ec2-user ec2-user 4096 Nov  3 15:20 /cvmfs/pilot.eessi-hpc.org/2020.10/compat/x86_64/lib64
```
Likewise for `/usr/{lib,lib64}`.

This is a problem, because some tools (like `CMake`, cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/2248) only looks in `lib`, and then fail to find libraries located in `lib64` if `lib` is not a symlink to it (like in `compat/aarch64`)...

Relevant links from Gentoo Prefix documentation:
* https://wiki.gentoo.org/wiki/Project:AMD64/Multilib_layout

**Comment by boegel** [comment]
It seems like Gentoo Prefix is moving away from using `SYMLINK_LIB=yes`, which we seem to have enabled for `x86_64`, but not for `aarch64`.

So while it's tempting to just make the Prefix installation procedure symlink `lib` to `lib64`, it may be better to actually sort out the problems we're seeing, rather than use this workaround as a quick escape hatch and then suffer later when it's no longer supported...

**Comment by olifre** [comment]
> It seems like Gentoo Prefix is moving away from using `SYMLINK_LIB=yes`, which we seem to have enabled for `x86_64`, but not for `aarch64`.

For reference, the upstream bug tracking this is: https://bugs.gentoo.org/640186

**Comment by terjekv** [comment]
I found this interesting:

```
SYMLINK_LIB=yes controls lib -> lib64 symlink. With SYMLINK_LIB=no, lib and lib64 are separate paths (and all libraries are required to go to lib64, as we already enforce with multilib-strict).
```

**Comment by bedroge** [comment]
I think our latest pilot (`2020.12`), which now uses the new Gentoo profile, "solves" this: both the `x86_64` and `aarch64` don't have this symlink anymore, so they look the same now.

```
$ ls /cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/x86_64/ -l
total 69433
drwxrwxr-x  2 cvmfs cvmfs     4096 dec 13 14:41 bin
drwxrwxr-x 35 cvmfs cvmfs     4096 dec 13 14:42 etc
drwxr-xr-x  6 cvmfs cvmfs     4096 dec 13 14:36 lib
drwxr-xr-x  3 cvmfs cvmfs     4096 dec 13 14:41 lib64
drwxr-xr-x  2 cvmfs cvmfs     4096 dec 13 12:34 run
drwxr-xr-x  2 cvmfs cvmfs     4096 dec 13 14:41 sbin
-rw-rw-r--  1 cvmfs cvmfs  2338107 dec 13 12:19 stage1.log
-rw-rw-r--  1 cvmfs cvmfs 14248112 dec 13 12:34 stage2.log
-rw-rw-r--  1 cvmfs cvmfs 54467019 dec 13 13:12 stage3.log
-rwxr-xr-x  1 cvmfs cvmfs     3623 dec 13 14:22 startprefix
drwxrwxr-x  2 cvmfs cvmfs     4096 dec 13 14:22 tmp
drwxrwxr-x 12 cvmfs cvmfs     4096 dec 13 14:31 usr
drwxrwxr-x  8 cvmfs cvmfs     4096 dec 13 15:21 var

$ ls /cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/aarch64/ -l
total 64596
drwxrwxr-x  2 cvmfs cvmfs     4096 dec 13 14:03 bin
drwxrwxr-x 35 cvmfs cvmfs     4096 dec 13 14:03 etc
drwxr-xr-x  6 cvmfs cvmfs     4096 dec 13 13:59 lib
drwxr-xr-x  3 cvmfs cvmfs     4096 dec 13 14:03 lib64
drwxr-xr-x  2 cvmfs cvmfs     4096 dec 13 12:02 run
drwxr-xr-x  2 cvmfs cvmfs     4096 dec 13 14:03 sbin
-rw-rw-r--  1 cvmfs cvmfs  2347835 dec 13 11:48 stage1.log
-rw-rw-r--  1 cvmfs cvmfs 13818368 dec 13 12:02 stage2.log
-rw-rw-r--  1 cvmfs cvmfs 49933681 dec 13 12:37 stage3.log
-rwxr-xr-x  1 cvmfs cvmfs     3631 dec 13 13:45 startprefix
drwxrwxr-x  2 cvmfs cvmfs     4096 dec 13 13:45 tmp
drwxrwxr-x 12 cvmfs cvmfs     4096 dec 13 13:54 usr
drwxrwxr-x  8 cvmfs cvmfs     4096 dec 13 15:21 var
```

**Comment by olifre** [comment]
Indeed, I see only now the prefix is built with `17.1` profiles in `2020.12`, that means `SYMLINK_LIB=no` is used :+1: .

**Comment by terjekv** [comment]
This should also make our RPATHs look better.

**Comment by boegel** [comment]
That just means that the issues we saw with CMake (which only looks in `lib`, not `lib64`), which are fixed with https://github.com/easybuilders/easybuild-easyblocks/pull/2248, will not be consistent on both `x86_64` and `aarch64` (which is better than inconsistent, I guess ;) ).

**Comment by bedroge** [comment]
@boegel I think we can close this issue, as the "real" CMake issue is being discussed in https://github.com/EESSI/software-layer/issues/36?

The `lib` and `lib64` directories now look the same on all architectures:
```
$ ls -ld /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/{aarch64,x86_64,ppc64le}/{lib,lib64}
drwxr-xr-x 6 cvmfs cvmfs 4096 feb 28 16:29 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/aarch64/lib
drwxr-xr-x 3 cvmfs cvmfs 4096 feb 28 16:36 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/aarch64/lib64
drwxr-xr-x 6 cvmfs cvmfs 4096 feb 24 21:29 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/ppc64le/lib
drwxr-xr-x 3 cvmfs cvmfs 4096 feb 24 21:52 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/ppc64le/lib64
drwxr-xr-x 6 cvmfs cvmfs 4096 feb 24 12:59 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/x86_64/lib
drwxr-xr-x 3 cvmfs cvmfs 4096 feb 24 13:07 /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/x86_64/lib64

```

**Comment by bedroge** [comment]
As far as I know, this has been solved, so I'm closing the issue.
