### ISSUE TITLE
automate build of container images used to bootstrap Prefix + use GitHub Container Registry

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#66]
Rebuilding the Docker images available at https://hub.docker.com/r/eessi/bootstrap-prefix/tags is now done "manually" (using the `docker_build_bootstrap_prefix.sh` script from this repo), this should be done automatically (for example when a new version is tagged in this repo).

We should also consider switching to the [GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry).

**Comment by bedroge** [comment]
Maybe too late for `2021.02`, but it would be nice to change this and build these images automatically.

@ChristianKniep mentioned something about Amazon ECR this morning (when you hadn't joined the meeting yet), maybe we can also use that? Seems to work with Singularity as well.

**Comment by bedroge** [comment]
Done in https://github.com/EESSI/compatibility-layer/pull/98.
