### ISSUE TITLE
additional Python packages to install in compat layer

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#72]
* `pip` (to install ReFrame on top of "system" Python)
* `GitPython` + `keyring` + `keyrings.alt` (for [EasyBuild GitHub integration](https://docs.easybuild.io/en/latest/Integration_with_GitHub.html#requirements))
* `pycodestyle` (for `eb --check-style`)

**Comment by boegel** [comment]
@peterstol @bedroge Are these available easily via Gentoo Prefix? `pycodestyle` is less important

**Comment by peterstol** [comment]
dev-python/pip
dev-python/GitPython
dev-python/keyring
dev-python/pycodestyle
Can easily be emerged (tested on a fresh prefix).

keyrings.alt can be installed in a user environment
pip install --user keyrings.alt

**Comment by terjekv** [comment]
`keyrings.alt` has some security implications that probably make it a good idea to not ship it as default:

> Keyrings in this package may have security risks or other implications. These backends were extracted from the main keyring project to make them available for those who wish to employ them, but are discouraged for general production use. Include this module and use its backends at your own risk.

**Comment by boegel** [comment]
@terjekv I'm not sure that a software package which allows doing insecure things should not be installed. With that type of reason, we shouldn't install Python or a C++ compiler either. ;)

**Comment by terjekv** [comment]
You say that as if removing python and C++ would be a bad thing...

**Comment by bedroge** [comment]
But I can't find a (recent) ebuild for that package either.
Apparently gentoo used to have one, see this old commit:
https://cgit.gentoo.org/repo/gentoo.git/plain/dev-python/keyrings_alt/?id=c913bb44bdb3e4463e1987c2bfe541364e987963
That entire folder doesn't exist anymore in their current repo, though.

Do we first skip it?

**Comment by peterstol** [comment]
closed by https://github.com/EESSI/gentoo-overlay/pull/11
