### ISSUE TITLE
playbook should only declare success if $EPREFIX/startprefix is there

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#79]
`startprefix` was missing in `2021.02` compat layer for `aarch64` for some reason, and this was not detected by the playbook...

**Comment by boegel** [comment]
The installation of the 2021.02 compat layer had to be restarted for `aarch64` and `ppc64le` because of https://github.com/EESSI/gentoo-overlay/issues/26, which seemed to be responsible for the missing `startprefix` in `2021.02/compat/linux/aarch64`.

However, when the crash happened (in the `Install package set` task), `startprefix` is already there for me...

**Comment by bedroge** [comment]
`startprefix` should indeed already be there, as it gets installed during the Prefix bootstrap, and the crash happens in a completely different step. Could it be that the `aarch64` also crashed during the bootstrap?

**Comment by bedroge** [comment]
I also had to restart the playbook on `ppc64le` (due to https://github.com/EESSI/gentoo-overlay/issues/26), but this installation does have the `startprefix` script.
