### ISSUE TITLE
/etc/localtime is missing in 2021.03 compat layer

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#93]
This causes timezone confusion for some software, see https://github.com/EESSI/software-layer/issues/79 .

We do have `/etc/localtime` in the `2020.12` compat layer:

```
cat /cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/x86_64/etc/localtime
TZif2-00TZif2-00
<-00>0
```

We should make this a symlink into the host, to get correct time zone information?

```
ln -s /etc/localtime /cvmfs/pilot.eessi-hpc.org/2021.03/compat/linux/x86_64/etc/localtime
```

**Comment by bedroge** [comment]
Apparently this was caused by an update of `sys-libs/timezone-data`, see https://github.com/gentoo/gentoo/commit/c4bf9520768aa3db2263303094504ac66871050f#diff-6b1379cb55d60e0b6dc6cc2be8a09b90cf10e403b82bc8c825fef1ccc18717ad

**Comment by boegel** [comment]
@bedroge This one was fixed somehow, right? (how?)
So we can close it?

**Comment by bedroge** [comment]
I wasn't sure if we had already fixed it, but I don't see the symlink here, so I guess it hasn't been fixed: 
https://github.com/EESSI/compatibility-layer/blob/main/ansible/playbooks/roles/compatibility_layer/defaults/main.yml#L52

**Comment by boegel** [comment]
We danced around this problem by defining `$TZ` where is matters (when installing `R`, since this was breaking the installation of the `rstan` instance), see https://github.com/EESSI/software-layer/commit/86e5ca9bf296626cbca4e0172fe04b62b528e8d3 .

For the next iteration of the EESSI pilot, we should fix this, so we can stopping setting `$TZ` when installing `R`...
