### ISSUE TITLE
add PyYAML to compat layer

### ISSUE THREAD

**Issue by boegel** [EESSI/compatibility-layer#95]
EasyBuild requires `PyYAML` for the easystack file support, so it would be nice to have this installed in the compat layer.

**Comment by bedroge** [comment]
That should be easy: https://github.com/gentoo/gentoo/tree/master/dev-python/pyyaml/
I guess the version doesn't matter, i.e. we can just go for the latest one?

**Comment by boegel** [comment]
Jup, latest is fine.
